app/forms/project.py
from wtforms.validators import ValidationError
from wtforms_alchemy import ModelForm

from app.models import Project


class ProjectForm(ModelForm):
    class Meta:
        model = Project

    def validate_title(form, field):
        project = Project.query.filter_by(title=field.data).first()
        print(
            'ProjectForm.validate_title() field.data:', field.data,
            'project:', project
        )
        # set in project.routes.edit()
        if project and project.id != form.__dict__.get('_project_id'):
            raise ValidationError('Name already exists')

app/views/comment.py
from flask import (
    Blueprint, flash, redirect, request, url_for
)
from flask_login import current_user, login_required

from app.models import Comment


commentbp = Blueprint('commentbp', __name__, url_prefix='/comment')


@commentbp.route('/submit/', methods=['POST'])
@login_required
def submit():
    content = request.form
    print('comment.submit() content:', content)
    comment = content.get('comment')
    project_id = content.get('project_id')
    parent_id = content.get('parent_id')
    user_id = current_user.id
    if comment and project_id and user_id:
        comment = Comment(
            text=comment,
            project_id=project_id,
            created_by_user_id=user_id,
            parent_id=parent_id
        )
        comment.save()
        flash('Added comment')
    else:
        flash('Unable to add comment', 'error')
    return redirect(url_for('projectbp.view', project_id=project_id))

app/views/project.py
from pprint import pformat

from flask import (
    abort, Blueprint, flash, render_template, redirect, request, url_for, flash
)
from flask_login import current_user, login_required
from slugify import slugify
from sqlalchemy import inspect

from app import db
from app.forms.project import ProjectForm
from app.models import Project


projectbp = Blueprint('projectbp', __name__, url_prefix='/projects')


@projectbp.route('/submit/', methods=['GET', 'POST'])
@login_required
def submit():
    form = ProjectForm(formdata=request.form)
    was_submitted = request.method == 'POST'
    print('project.submit() was_submitted:', was_submitted)               ,
    if was_submitted:
        is_valid = form.validate()
        if is_valid:
            project_dict = {
                'title': form.title.data,
                'description': form.description.data,
                'needed': form.needed.data,
                'provided': form.provided.data,
                'contact': form.contact.data,
                'created_by_user_id': current_user.id,                                               'created_by_user': current_user,
                'users_joined': [current_user]
            }
            print('project.submit() project_dict:', project_dict)
            project = Project(**project_dict)
            db.session.add(project)
            db.session.commit()
            return redirect(url_for('projectbp.view', project_id=project.id))
        else:
            flash(
                'There was an error with your submission, please try again',
                'error'
            )

    return render_template(
        'project/submit.html',
        title='Submit a Project',
        action='submit',
        form=form,
        is_invalid=was_submitted and (not is_valid)
    )

@projectbp.route('/<project_id>/', methods=['GET', 'POST'])
@projectbp.route('/<project_id>/<user_slug>/', methods=['GET', 'POST'])
def view(project_id, user_slug=None):
    print('project_id:', project_id)
    print('user_slug:', user_slug)
    project = Project.query.filter_by(id=project_id).first()
    if not project:
        return abort(404)
    slug = slugify(project.title)
    if slug != user_slug:
        return redirect(url_for(
            'projectbp.view', project_id=project_id, user_slug=slug
        ))
    columns = [c for c in inspect(Project).columns]

    # XXX hack
    # TODO: figureout how to do this with wtforms_alchemy
    field_by_key = {
        column.key: {
            'label': column.info.get('label'),
            'data': getattr(project, column.key)
        }
        for column in inspect(Project).columns
        if not column.key.endswith('id')
        and not 'timestamp' in column.key
        and not 'title' in column.key
    }

    return render_template(
        'project/view.html',
        title=project.title,
        project=project,
        field_by_key=field_by_key
    )


@projectbp.route('/', methods=['GET', 'POST'])
def list():
    projects = Project.query.all()
    return render_template(
        'project/list.html', title='List Projects', projects=projects
    )

@projectbp.route('/join/<project_id>/', methods=['GET', 'POST'])
@login_required
def join(project_id):
    project = Project.query.filter_by(id=project_id).first()
    if not project:
        flash('No such project exists', 'error')
    else:
        if current_user in project.users_joined:
            # if user tried to join a project they were already a part of
            # while they were signed out, don't remove them
            if url_for('userbp.signin') in request.referrer:
                flash('You have already joined this project')
            else:
                project.users_joined.remove(current_user)
                flash('You have left the project')
        else:
            project.users_joined.append(current_user)
            flash('You have joined the project')
        db.session.commit()
    return redirect(url_for('projectbp.view', project_id=project.id))


@projectbp.route('/<project_id>/edit/', methods=['GET', 'POST'])
@projectbp.route('/<project_id>/<user_slug>/edit/', methods=['GET', 'POST'])
@login_required
def edit(project_id, user_slug=None):
    project = Project.query.filter_by(id=project_id).first()
    if not project:
        flash('No such project exists', 'error')
        return redirect(url_for('projectbp.list'))

    if not (
        current_user.is_superadmin or
        current_user.id == project.created_by_user_id
    ):
        flash('You don\'t have permission to do that')
        return redirect(url_for('projectbp.view', project_id=project_id))

    if request.method == 'GET':
        form = ProjectForm(obj=project)
        form.populate_obj(project)
    else:
        form = ProjectForm(formdata=request.form)

    # XXX HACK
    # read in project.forms.SubmitProjectForm.validate_title()
    form._project_id = int(project_id)

    was_submitted = request.method == 'POST'
    print(
        'project.edit() form:', form,
        'request.method:', request.method,
        'was_submitted:', was_submitted
    )
    if was_submitted:
        is_valid = form.validate()
        if is_valid:
            print('form:', pformat(vars(form)))
            project_dict = {
                'title': form.title.data,
                'description': form.description.data,
                'needed': form.needed.data,
                'provided': form.provided.data,
                'contact': form.contact.data,
                'budget': form.budget.data,
                'decision_making': form.decision_making.data
            }
            print('project.submit() project_dict:', project_dict)
            for key, val in project_dict.items():
                setattr(project, key, val)
            db.session.commit()
            return redirect(url_for(
                'projectbp.view',
                project_id=project_id,
                user_slug=slugify(project.title)
            ))
        else:
            flash(
                'There was an error with your submission, please try again',
                'error'
            )
    else:
        is_valid = True
    submission_is_invalid = (not is_valid) and was_submitted
    return render_template(
        'project/submit.html',
        title='Edit',
        action='edit',
        form=form,
        project=project,
        is_invalid=submission_is_invalid
    )


@projectbp.route('/delete/<project_id>/', methods=['POST'])
def delete(project_id):
    project = db.session.query(Project).filter(Project.id==project_id).first()
    print('project.delete() project:', project)
    db.session.delete(project)
    db.session.commit()
    flash('Project was deleted')
    return redirect(url_for('projectbp.list'))

app/templates/project/list.html
{% extends "layout.html" %}

{% block head %}

{{ super() }}

<style>

.project-summaries {
  max-width: 500px;
  margin: 0 auto;
}

.project-summary .header {
  margin: 0 0 .5em !important;
}

.project-summary p {
  margin: 1em 0 !important;
}

</style>

{% endblock %}


{% block actions %}


<div class="ui container">
  <a href="{{ url_for('projectbp.submit') }}">
    <div class="ui button">
      <i class="plus icon"></i>
      New Project
    </div>
  </a>
</div>


{% endblock %}


{% block content %}

<div class="ui container">
  {% if projects %}
    <div class="project-summaries">
      {% for project in projects %}
        <div class="project-summary ui card fluid text segment">
          <div class="content">
            <div class="header">
              {{ project.title }}
            </div>
            <a
              class="ui label"
              href="{{
                url_for(
                  'projectbp.view',
                  project_id=project.id,
                  user_slug=slugify(project.title)
                )
              }}"
            />
              {{ project.users_joined|length }}
              {{ 'members' if project.users_joined|length != 1 else 'member' }}
            </a>
            <a
              class="ui label"
              href="{{
                url_for(
                  'projectbp.view',
                  project_id=project.id,
                  user_slug=slugify(project.title)
                )
              }}#comments"
            />
              {{ project.comments|length }}
              {{ 'comments' if project.comments|length != 1 else 'comment' }}
            </a>
            <div class="card">
              <div class="card-body">
                <p>
                  {{ project.description }}
                </p>
                <a
                  href="{{
                    url_for(
                      'projectbp.view',
                      project_id=project.id,
                      user_slug=slugify(project.title)
                    )
                  }}"
                >
                  <div class="ui primary button">
                    Open
                    <i class="right arrow icon"></i>
                  </div>
                </a>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  {% else %}
    <h1>No projects found!</h1>
  {% endif %}
</div>

{% endblock %}

app/templates/project/submit.html
{% extends "layout.html" %}


{% block head %}

{{ super() }}

<style>

textarea {
  height: 6em !important;
}

</style>

{% endblock %}


{% block actions %}

<div class="ui container">
  <a href="{{ url_for('projectbp.list') }}">
    <div class="ui button">
      <i class="left arrow icon"></i>
      List Projects
    </div>
  </a>
</div>

{% endblock %}


{% block content %}

<div class="ui container segment">
  <form
    class="ui form fluid"
    action="{{
      url_for(
        'projectbp.{}'.format(action),
        project_id=project.id if project else None,
        user_slug=slugify(project.title) if project else None
      )
    }}"
    method="post"
  >
    <h2 class="ui header">
      {{ 'Edit' if project and project.id else 'Submit' }} Project
    </h2>
    <!--div class="ui ignored positive icon message"-->
    <span class="meta">
      This information will be public.
    </span>
    <div class="ui divider"></div>
    {{ m.render_expanded_field(form.title) }}
    <div class="ui divider"></div>
    {{ m.render_expanded_field(form.description) }}
    <div class="ui divider"></div>
    {{ m.render_expanded_field(form.needed) }}
    <div class="ui divider"></div>
    {{ m.render_expanded_field(form.provided) }}
    <div class="ui divider"></div>
    {{ m.render_expanded_field(form.contact) }}
    <div class="ui divider"></div>
    {{ m.render_expanded_field(form.budget) }}
    <div class="ui divider"></div>
    {{ m.render_expanded_field(form.decision_making) }}
    {{ form.csrf_token }}
    <button
      class="ui primary button"
      type="submit"
    >
      Submit
    </button>
  </form>
</div>

{% endblock %}

app/templates/project/view.html
{% extends "layout.html" %}


{% block head %}

{{ super() }}

<style>

textarea {
  height: 6em !important;
}

#project-actions form {
  display: inline-block;
}

.comment-box label {
  font-weight: normal !important;
}
.comment-box button[type=submit],
.reply-box button[type=submit]
{
  margin-top: 10px !important;
}

.hidden {
  display: none;
}
.ui.comments .comment>.comments {
  padding-bottom: 0 !important;
}

.comment-box .meta {
  margin-bottom: 5px;
}

.CodeMirror, .CodeMirror-scroll {
  min-height: 100px !important;
}

.editor-toolbar:before,
.editor-toolbar:after {
  margin: 0 !important;
}

div.comments {
  border-left: 1px dotted #ccc;
}
.comment-container.comments {
  border-left: none;
}

/* hack to get around extra leading and trailing paragraphs */
.comment p:empty {
  display: none;
}
.comment p:nth-last-of-type(2) {
  margin-bottom: 0;
}

</style>

<script>

var commentEditor
var replyEditor

$(document).on('turbolinks:load', onTurbolinksLoad)
$(document).on('turbolinks:click', onTurbolinksClick)


function isEmpty(el){
  return !$.trim(el.html())
}

function onTurbolinksLoad() {
  console.log('onTrubolinksLoad()')
  initCommentEditor()
  initReplyLinks()
  initDeleteConfirmation()
}

function onTurbolinksClick() {
  console.log('onTurbolinksClick()')
  // Without this we get multiple comment boxes when navigating back
  unloadCommentEditor()
  // Reply boxes are only created on click, not by default on page load.
  // Unloading results in an empty textarea when navigating back.
}

function initCommentEditor() {
  let commentElement = document.getElementById('comment')
  console.log('initCommentEditor() commentElement:', commentElement)
  // The user may have loaded this header via a direct link, in which case
  // this will be null when they navigate away
  if (commentElement) {
    commentEditor = new SimpleMDE({
      element: commentElement,
      hideIcons: ['side-by-side'],
      status: false
    })
  }
}

function initReplyLinks() {
  console.log('initReplyLinks()')
  $('.reply-link').click((e) => {
    console.log('click e:', e)
    let $replyLink = $(e.currentTarget)
    let $comment = $replyLink.closest('.comment')
    console.log('$comment:', $comment)
    let $comments = $comment.find('.comments:first')
    console.log('$comments:', $comments)
    let $replies = $('.comments .reply-box')
    console.log('$replies:', $replies)
    console.log('$replies.length', $replies.length)
    if ($replies.length) {
      replyEditor.toTextArea()
      $replies.remove()
      if (isEmpty($comments)) {
        $comments.hide()
      }
    }
    let $replyBox = $('.hidden .reply-box')
    console.log('$replyBox:', $replyBox)
    let $clone = $replyBox.clone()
    console.log('$clone:', $clone)
    let parentId = $replyLink.data('parent-id')
    console.log('parentId:', parentId)
    let $parentId = $clone.find('.parent_id')
    console.log('$parentId:', $parentId)
    $parentId.val(parentId)
    $comments.prepend($clone)
    $comments.show()
    let $reply = $clone.find('textarea.reply')
    let reply = $reply[0]
    console.log('$reply:', $reply, 'reply:', reply)
    replyEditor = new SimpleMDE({
      element: $reply[0],
      hideIcons: ['side-by-side'],
      status: false
    })
  })
}

function unloadCommentEditor() {
  if (commentEditor) {
    commentEditor.toTextArea()
    commentEditor = null
  }
}

function initDeleteConfirmation() {
  $('#delete-button').click((e) => {
    let result = confirm('Are you sure? This cannot be undone!')
    console.log('initDeleteConfirmation() result:', result)
    if (!result) {
      e.preventDefault()
    }
  })

}

</script>



{% endblock %}


{% block actions %}

<div class="ui container">
  <a href="{{ url_for('projectbp.list') }}">
    <div class="ui button">
      <i class="left arrow icon"></i>
      List Projects
    </div>
  </a>
  <a href="{{ url_for('projectbp.submit') }}">
    <div class="ui button">
      <i class="plus arrow icon"></i>
      New Project
    </div>
  </a>
</div>


{% endblock %}


{% block content %}

<div class="ui container segment">
  <h2 class="ui header">{{ project.title }}</h2>
  <div class="content">
    <div class="num-users">
      <p class="meta">
        {{ project.users_joined|length }}
        {{ 'members' if project.users_joined|length != 1 else 'member' }}
      </p>
      <p>
        {% for user in project.users_joined %}
          <a
            href="{{
              url_for('userbp.view', user_id=user.id )
            }}"
            class="ui horizontal label"
          >
            {{ user.full_name }}
          </a>
        {% endfor %}
      </p>
    </div>
    <div class="ui divider"></div>
    {% for key, field in field_by_key.items() %}
      <div class="ui aligned four wide stackable grid">
        <div class="ui four wide column">
          <strong>
            {{ field['label'] }}
          </strong>
        </div>
        <div class="eight wide column">
          {{ field['data'] or '-' }}
        </div>
      </div>
      <div class="ui divider"></div>
    {% endfor %}
    <div id="project-actions">
      <form
        method="post"
        action="{{ url_for('projectbp.join', project_id=project.id) }}"
      >
        <button class="ui primary button" type="submit">
          {% if current_user in project.users_joined %}
            <i class="remove user icon"></i>
            Leave
          {% else %}
            <i class="add user icon"></i>
            Join
          {% endif %}
        </button>
      </form>
      {%
        if current_user.is_superadmin or
        project.created_by_user_id == current_user.id
      %}
        <form
          method="get"
          action="{{ url_for(
              'projectbp.edit',
              project_id=project.id,
              user_slug=slugify(project.title)
          ) }}"
        >
          <button class="ui green button" type="submit">
            <i class="edit icon"></i>
            Edit
          </button>
        </form>
        <form
          method="post"
          action="{{
            url_for('projectbp.delete', project_id=project.id)
          }}"
        >
          <button
            id="delete-button"
            class="ui red button"
            type="submit"
          >
            <i class="icon remove"></i>
            Delete
          </button>
        </form>
      {% endif %}
    </div>
  </div>
</div>


<div class="ui container segment">
  <h3 class="ui header">
    Comments
  </h3>
  {% if current_user.is_authenticated %}
    <div class="comment-box">
      <div class="ui form">
        <label>
          <p class="meta">
            Comment as
            <a href="{{ url_for('userbp.view', user_id=current_user.id) }}">
              {{ current_user.full_name }}
            </a>
          </p>
        </label>
        <form
          method="post"
          action="{{ url_for('commentbp.submit') }}"
        >
          <input type="hidden" name="project_id" value="{{ project.id }}" />
          <textarea rows="2" name="comment" id="comment"></textarea>
          <!-- #comments scrolls here to account for header -->
          <button
            id="comments"
            class="ui primary button"
            type="submit"
          >
            <i class="comment icon"></i>
            Comment
          </button>
        </form>
      </div>
    </div>
  {% else %}
    <p>
      {{ m.nav_link('userbp.signin', 'Sign In') }}
      or
      {{ m.nav_link('userbp.signup', 'Sign Up') }}
      to leave a comment.
    </p>
  {% endif %}
  <div class="comment-container ui comments">
    {% if project.comments %}
      {% for comment in project.comments %}
        {% if not comment.parent %}
          {{ make_comment(comment) }}
        {% endif %}
      {% endfor %}
    {% else %}
      <p>
        No comments yet. Be the first to share what you think!
      </p>
    {% endif %}
  </div>
</div>

<div class="hidden">
  <div class="reply-box">
    <div class="comment">
      <a class="avatar"></a>
      <div class="content">
        <div class="ui reply form">
          <form
            method="post"
            action="{{ url_for('commentbp.submit') }}"
          >
            <input
              type="hidden"
              class="project_id"
              name="project_id"
              value="{{ project.id }}"
            />
            <input type="hidden" class="parent_id" name="parent_id" />
            <textarea rows="2" name="comment" class="reply"></textarea>
            <button class="ui primary button" type="submit">
              <i class="comments icon"></i>
              Reply
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% macro make_comment(comment) %}

<div class="comment">
  <a class="avatar">
    <img src="/static/img/avatar.png">
  </a>
  <div class="content">
    <a
      class="author"
      href="{{
        url_for('userbp.view', user_id=comment.created_by_user.id)
      }}"
    >
      {{ comment.created_by_user.full_name }}
    </a>
    <div class="metadata">
      <span class="date">
        {{ comment.age }}
      </span>
    </div>
    <div class="text">
      <!-- tag and text must be on same line for :empty -->
      <p>{{ comment.text|markdown }}</p>
    </div>
    <div class="actions">
      <a class="reply-link" data-parent-id="{{ comment.id }}">Reply</a>
    </div>
  </div>
  <div class="comments {{ 'hidden' if not comment.replies.count() else '' }}">
  {% if comment.replies %}
    {% for reply in comment.replies %}
      {{ make_comment(reply) }}
    {% endfor %}
  {% endif %}
  </div>
</div>

{% endmacro %}