app/forms/user.py
from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField
from wtforms.validators import Required, Length, Email, EqualTo
from app.forms import Unique
from app.models import User


class Forgot(FlaskForm):

    ''' User forgot password form. '''

    email = TextField(
        validators=[Required(), Email()],
        description='Email address')


class Reset(FlaskForm):

    ''' User reset password form. '''

    password = PasswordField(
        validators=[
            Required(),
            Length(min=6),
            EqualTo('confirm', message='Passwords must match.')
        ],
        description='Password'
    )
    confirm = PasswordField(description='Confirm password')


class Login(FlaskForm):

    ''' User login form. '''

    email = TextField(
        validators=[Required(), Email()],
        description='Email'
    )
    password = PasswordField(
        validators=[Required()],
        description='Password'
    )


class SignUp(FlaskForm):

    ''' User sign up form. '''

    first_name = TextField(
        description='First Name',
        validators=[Required(), Length(min=2)],
    )
    last_name = TextField(description='Last Name')
    email = TextField(
        description='Email address',
        validators=[
            Required(),
            Email(),
            Unique(
                User,
                User.email,
                'This email address is already linked to an account.'
            )
        ],
    )
    password = PasswordField(
        description='Password',
        validators=[
            Required(),
            Length(min=6),
            EqualTo('confirm', message='Passwords must match.')
        ],
    )
    confirm = PasswordField(description='Confirm password')

app/views/user.py
from flask import (
    abort, Blueprint, flash, render_template, redirect, request, url_for
)
from flask_login import current_user, login_user, logout_user, login_required
from itsdangerous import URLSafeTimedSerializer
from app import app, models, db
from app.forms import user as user_forms
from app.toolbox import email

# Serializer for generating random tokens
ts = URLSafeTimedSerializer(app.config['SECRET_KEY'])

# Create a user blueprint
userbp = Blueprint('userbp', __name__, url_prefix='/user')


@userbp.route('/signup', methods=['GET', 'POST'])
def signup():
    form = user_forms.SignUp()
    if form.validate_on_submit():
        # Create a user who hasn't validated his email address
        user = models.User(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data,
            confirmation=False,
            password=form.password.data,
        )
        # Insert the user in the database
        db.session.add(user)
        db.session.commit()
        # Subject of the confirmation email
        subject = 'Please confirm your email address.'
        # Generate a random token
        token = ts.dumps(user.email, salt='email-confirm-key')
        # Build a confirm link with token
        confirmUrl = url_for('userbp.confirm', token=token, _external=True)
        # Render an HTML template to send by email
        html = render_template('email/confirm.html',
                               confirm_url=confirmUrl)
        # Send the email to user
        email.send(user.email, subject, html)
        # Send back to the home page
        flash('Check your email to confirm your email address.', 'info')
        next_url = request.args.get('next', url_for('index'))
        return redirect(next_url)
    return render_template('user/signup.html', form=form, title='Sign up')


@userbp.route('/confirm/<token>', methods=['GET', 'POST'])
def confirm(token):
    try:
        email = ts.loads(token, salt='email-confirm-key', max_age=86400)
    # The token can either expire or be invalid
    except:
        abort(404)
    # Get the user from the database
    user = models.User.query.filter_by(email=email).first()
    # The user has confirmed his or her email address
    user.confirmation = True
    # Update the database with the user
    db.session.commit()
    # Send to the signin page
    flash(
        'Your email address has been confirmed, you can sign in.', 'info'
    )
    return redirect(url_for('userbp.signin'))


@userbp.route('/signin', methods=['GET', 'POST'])
def signin():
    form = user_forms.Login()
    next_url = request.args.get('next', url_for('index'))
    print('signin() next_url:', next_url)
    if form.validate_on_submit():
        user = models.User.query.filter_by(email=form.email.data).first()
        if user is not None:
            if user.check_password(form.password.data):
                login_user(user)
                flash('Successfully signed in.', 'info')
                return redirect(next_url)
            else:
                flash('The password you have entered is wrong.', 'error')
                return redirect(url_for('userbp.signin', next=next_url))
        else:
            flash('Unknown email address.', 'error')
            return redirect(url_for('userbp.signin', next=next_url))
    return render_template('user/signin.html', form=form, title='Sign in')


@userbp.route('/signout')
def signout():
    logout_user()
    flash('Successfully signed out.', 'info')
    next_url = request.args.get('next', url_for('index'))
    print('signout() next_url:', next_url)
    return redirect(next_url)


@userbp.route('/account')
@login_required
def account():
    return render_template(
        'user/account.html', user=current_user, title='Account'
    )


@userbp.route('/forgot', methods=['GET', 'POST'])
def forgot():
    form = user_forms.Forgot()
    if form.validate_on_submit():
        user = models.User.query.filter_by(email=form.email.data).first()
        # Check the user exists
        if user is not None:
            # Subject of the confirmation email
            subject = 'Reset your password.'
            # Generate a random token
            token = ts.dumps(user.email, salt='password-reset-key')
            # Build a reset link with token
            resetUrl = url_for('userbp.reset', token=token, _external=True)
            # Render an HTML template to send by email
            html = render_template('email/reset.html', reset_url=resetUrl)
            # Send the email to user
            email.send(user.email, subject, html)
            # Send back to the home page
            flash(
                'Please check your email to reset your password.',
                'info'
            )
            return redirect(url_for('index'))
        else:
            flash('Unknown email address.', 'error')
            return redirect(url_for('userbp.forgot'))
    return render_template('user/forgot.html', form=form)


@userbp.route('/reset/<token>', methods=['GET', 'POST'])
def reset(token):
    try:
        email = ts.loads(token, salt='password-reset-key', max_age=86400)
    # The token can either expire or be invalid
    except:
        abort(404)
    form = user_forms.Reset()
    if form.validate_on_submit():
        user = models.User.query.filter_by(email=email).first()
        # Check the user exists
        if user is not None:
            user.password = form.password.data
            # Update the database with the user
            db.session.commit()
            # Send to the signin page
            flash('Your password has been reset, you can sign in.', 'info')
            return redirect(url_for('userbp.signin'))
        else:
            flash('Unknown email address.', 'error')
            return redirect(url_for('userbp.forgot'))
    return render_template('user/reset.html', form=form, token=token)


@userbp.route('/view/<user_id>/', methods=['GET'])
def view(user_id):
    print('user.view() user_id:', user_id)
    user = models.User.query.filter_by(id=user_id).first()
    print('user.view() user:', user)
    projects = user.projects_created
    return render_template('user/account.html', user=user, projects=projects)

app/templates/user/account.html
{% extends "layout.html" %}

{% block head %}

{{ super() }}

<style>
#project-list {
  padding: 0;
}
#project-list li {
  list-style: none;
  margin-bottom: 5px;
}
dt {
  font-weight: bold;
}
</style>

{% endblock %}

{% block content %}

<div class="ui container segment">
  <h1 class="ui header">{{ user.full_name }}</h1>
  <dt>Projects Created</dt>
  <dd>
    {% if user.projects_created %}
      <ul id="project-list">
        {% for project in user.projects_created %}
          <li>
            <a
              href="{{ url_for('projectbp.view', project_id=project.id) }}"
              class="ui label"
            >
              {{ project.title }}
            </a>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      -
    {% endif %}
  </dd>
  <dt>Projects Joined</dt>
  <dd>
    {% if user.projects_joined %}
      <ul id="project-list">
        {% for project in user.projects_joined %}
          <li>
            <a
              href="{{ url_for('projectbp.view', project_id=project.id) }}"
              class="ui label"
            >
              {{ project.title }}
            </a>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      -
    {% endif %}
  </dd>
  {% if 0 %}
  <dt>Comments</dt>
  <dd>
    {% if user.comments_created %}
      <ul id="comment-list">
        {% for comment in user.comments_created %}
          <li>
            {{ comment.text }}
          </li>
        {% endfor %}
      </ul>
    {% endif %}
  <dd>
  {% endif %}
</div>

{% endblock %}

app/templates/user/forgot.html
{% extends "layout.html" %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block content %}

  <div class="ui form-user center raised text container segment">
    <form class="ui form" action="/user/forgot" method="POST">
      <h4 class="ui dividing header">
        Enter your email address so that we can send you a password reset link
      </h4>
      {{ m.render_field(form.email) }}
      {{ form.csrf_token }}
      <button class="ui primary button" type="submit">Confirm</button>
    </form>
  </div>

{% endblock %}

app/templates/user/reset.html
{% extends "layout.html" %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block content %}

  <div class="ui form-user center raised text container segment">
    <form
      class="ui form"
      action="{{ url_for('userbp.reset', token=token) }}"
      method="POST"
    >
      <h4 class="ui dividing header">Choose a new password</h4>
        {{ m.render_field(form.password) }}
        {{ m.render_field(form.confirm) }}
        {{ form.csrf_token }}
        <button class="ui primary button" type="submit">Confirm</button>
    </form>
  </div>

{% endblock %}

app/templates/user/signin.html
{% extends "layout.html" %}

{% block head %}
    {{ super() }}
{% endblock %}


{% block content %}

<div class="ui padded grid">
  <div class="five wide computer only column"></div>
  <div class="four wide tablet only column"></div>
  <div class="one wide mobile only column"></div>
  <div class="fourteen wide mobile eight wide tablet six wide computer column">
    <div class="ui raised text segment">
      <form
        class="ui form"
        action="{{
          url_for(
            'userbp.signin',
            next=request.args.get('next', url_for('index'))
          )
        }}"
        method="post"
      >
        <h4 class="ui dividing header">
          Login
        </h4>
        {{ m.render_field(form.email) }}
        {{ m.render_field(form.password) }}
        {{ form.csrf_token }}
        <button class="ui primary button" type="submit">Confirm</button>
        <a href="{{ url_for('userbp.forgot') }}">
          <div class="ui floated right basic red button">
              Forgot Password
          </div>
        </a>
        <p class="login-hint">
          Don't have an account?
          <a href="{{ url_for('userbp.signup') }}">Sign up</a>
        </p>
      </form>
    </div>
  </div>
</div>

{% endblock %}

app/templates/user/signup.html
{% extends "layout.html" %}

{% block content %}

<div class="ui padded grid">
  <div class="five wide computer only column"></div>
  <div class="four wide tablet only column"></div>
  <div class="one wide mobile only column"></div>
  <div class="fourteen wide mobile eight wide tablet six wide computer column">
    <div class="ui raised text segment">
      <form
        class="ui form"
        action="{{
          url_for(
            'userbp.signup',
            next=request.args.get('next', url_for('index'))
          )
        }}"
        method="post"
      >
        <h4 class="ui dividing header">Sign up</h4>
        {{ m.render_field(form.first_name) }}
        {{ m.render_field(form.last_name) }}
        {{ m.render_field(form.email) }}
        {{ m.render_field(form.password) }}
        {{ m.render_field(form.confirm) }}
        {{ form.csrf_token }}
        <button class="ui primary button" type="submit">Submit</button>
        <p class="login-hint">
          Already have an account?
          <a href="{{
            url_for('userbp.signin', next=request.args.get('next'))
          }}">
            Login
          </a>
        </p>
      </form>
    </div>
  </div>
</div>

{% endblock %}